#!/bin/bash
#
#BSUB -P sundials                # project to charge
#BSUB -W WTIME:00                # max wall time (hours)
#BSUB -nnodes NODES              # requested nodes
#BSUB -J NAME                    # job name
#BSUB -o stdout-%J.txt
#BSUB -e stderr-%J.txt
#BSUB -N                         # send email on job completion

# change to run directory
cd RUNDIR

# write timestamp to stdout
echo "  "
date

# ensure that appropriate modules are loaded
module load xl/2019.02.07
module load cmake
module load essl/6.2
module load hdf5-parallel/1.10.4
module load cuda/10.1.243
module load hpctoolkit/2019.03.10

# write loaded modules (sent to stderr)
module list

# set the 'jsrun' options [default value]:
#    number of resource sets  [all available physical cores]
JSRUN_N=RESOURCESETS
#    number of MPI tasks per resource set  [no default]
JSRUN_A=20
#    number of CPUs per resource set  [1]
JSRUN_C=20
#    number of GPUs per resource set  [0]
JSRUN_G=0
#    binding of tasks within a resource set (none / rs / packed:#)  [packed:1]
JSRUN_B=packed:1
#    number of resource sets per host  [no default]
JSRUN_R=2
#    latency priority (CPU-CPU / GPU-CPU)  [GPU-CPU,CPU-MEM,CPU-CPU]
JSRUN_L=CPU-CPU
#    how tasks are started on resource sets  [packed]
JSRUN_D=packed

# create jsrun command
CMD="jsrun -n $JSRUN_N -a $JSRUN_A -c $JSRUN_C -g $JSRUN_G -b $JSRUN_B -r $JSRUN_R -l $JSRUN_L -d $JSRUN_D ./primordial_blast_SUFFIX.exe --infile=input_primordial_blast_SUFFIX.txt"

# echo jsrun command to stdout
echo "  "
echo "jsrun command line:"
echo $CMD

# run the job
echo "  "
$CMD
